"""Generate a self-contained HTML file of the tasks related to a subject: each row
is the task NAME + NUMBER (hyperlinked to the issue), plus assignee, status, sprint,
and the last few comments. Read-only.

Usage:
    python scripts/related_tasks_html.py "<subject>" [OUT_DIR] [PROJECT]
        subject  free-text keywords (quote it if it has spaces) — required
        OUT_DIR  where to write the .html (default: current dir)
        PROJECT  restrict to a project short name, e.g. DEMO (optional)
"""
import os
import sys
import json
import html
import re

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass

from dotenv import load_dotenv

load_dotenv()

from youtrack_mcp.tools.composites import CompositeTools

BASE = (os.getenv("YOUTRACK_URL") or "").rstrip("/")

if len(sys.argv) < 2 or not sys.argv[1].strip():
    print('Usage: python scripts/related_tasks_html.py "<subject>" [OUT_DIR] [PROJECT]')
    sys.exit(1)

SUBJECT = sys.argv[1].strip()
OUT_DIR = sys.argv[2] if len(sys.argv) > 2 else "."
PROJECT = sys.argv[3] if len(sys.argv) > 3 else None
LIMIT = 5
COMMENTS = 5


def e(s):
    return html.escape("" if s is None else str(s))


CSS = """
:root{--dark:#1f2937;--slate:#374151;--zebra:#f7f8fa;--grid:#e5e7eb;
  --link:#1a56db;--muted:#6b7280}
*{box-sizing:border-box}
body{font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;
  color:#111827;margin:0;padding:32px;background:#f9fafb;line-height:1.45}
.wrap{max-width:1040px;margin:0 auto}
h1{font-size:22px;margin:0 0 2px}
.sub{color:var(--muted);font-size:13px;margin:0 0 16px}
table{border-collapse:collapse;width:100%;font-size:13px;background:#fff;
  box-shadow:0 1px 2px rgba(0,0,0,.04);border-radius:8px;overflow:hidden}
th,td{border:1px solid var(--grid);padding:8px 10px;text-align:left;
  vertical-align:top}
thead th{background:var(--dark);color:#fff;font-weight:600}
tbody tr:nth-child(even){background:var(--zebra)}
td.task{white-space:nowrap;font-weight:600}
a{color:var(--link);text-decoration:none}
a:hover{text-decoration:underline}
.num{font-weight:400;color:var(--muted)}
ul.cm{margin:0;padding-left:16px}
ul.cm li{margin:2px 0}
ul.cm .who{font-weight:600}
.empty{color:var(--muted);font-style:italic}
footer{color:var(--muted);font-size:12px;margin-top:24px;text-align:center}
"""


def comment_list(comments):
    if not comments:
        return '<span class="empty">—</span>'
    items = ""
    for c in comments:
        who = e(c.get("author"))
        txt = e((c.get("text") or "")[:200])
        items += f'<li><span class="who">{who}:</span> {txt}</li>'
    return f'<ul class="cm">{items}</ul>'


def main():
    ct = CompositeTools()
    print(f'Searching for "{SUBJECT}"' + (f" in {PROJECT}" if PROJECT else "") + " ...")
    res = json.loads(
        ct.related_issues(
            subject=SUBJECT, limit=LIMIT, comments=COMMENTS, project=PROJECT
        )
    )
    if res.get("error"):
        print("Error:", res["error"])
        sys.exit(1)
    issues = res.get("issues", [])

    rows = ""
    for i in issues:
        iid = i.get("id") or ""
        url = f"{BASE}/issue/{e(iid)}"
        name = e((i.get("summary") or "").strip())
        task = (
            f'<a href="{url}">{name} '
            f'<span class="num">— {e(iid)}</span></a>'
        )
        rows += (
            f'<tr><td class="task">{task}</td>'
            f"<td>{e(i.get('assignee')) or '—'}</td>"
            f"<td>{e(i.get('status')) or '—'}</td>"
            f"<td>{e(i.get('sprint')) or '—'}</td>"
            f"<td>{comment_list(i.get('comments'))}</td></tr>"
        )
    if not rows:
        rows = '<tr><td colspan="5" class="empty">No tasks found.</td></tr>'

    doc = f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Related tasks — {e(SUBJECT)}</title>
<style>{CSS}</style></head>
<body><div class="wrap">
<h1>Related tasks — &ldquo;{e(SUBJECT)}&rdquo;</h1>
<p class="sub">{len(issues)} found{f' &middot; project {e(PROJECT)}' if PROJECT else ''}
 &middot; click a task name to open it in YouTrack</p>
<table>
<thead><tr><th>Task</th><th>Assignee</th><th>Status</th><th>Sprint</th>
<th>Last comments</th></tr></thead>
<tbody>{rows}</tbody>
</table>
<footer>Generated by Jason-MCP · read-only</footer>
</div></body></html>"""

    slug = re.sub(r"[^a-zA-Z0-9]+", "-", SUBJECT).strip("-").lower() or "related"
    path = os.path.join(OUT_DIR, f"related-tasks-{slug}.html")
    os.makedirs(OUT_DIR, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(doc)

    print(f"  {len(issues)} tasks -> {path}")


if __name__ == "__main__":
    main()
